//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarKitchenApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StarKitchenEntities : DbContext
    {
        public StarKitchenEntities()
            : base("name=StarKitchenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientCredential> ClientCredentials { get; set; }
        public virtual DbSet<MailCredential> MailCredentials { get; set; }
        public virtual DbSet<ServicesCredential> ServicesCredentials { get; set; }
    }
}
